version: '3'
services:
  api:
    container_name: api_container_prod
    build:
      context: ./api
      dockerfile: Dockerfile
    image: opiq/dashboard_api
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - .env.production

  client:
    depends_on:
      - api
    container_name: client_container_prod
    build:
      context: ./client
      dockerfile: Dockerfile
    image: opiq/dashboard_client
    ports:
      - '3000:3000'
