version: '3.5'
services:
  api:
    container_name: api_container_dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: app_name/api_container_dev
    ports:
      - '5000:5000'
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - .env.development

  client:
    depends_on:
      - api
    container_name: client_container_dev
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: app_name/client_container_dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
